// front-end-angular/src/app/shared/search-bar/search-bar.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'search-bar',
  templateUrl: './search-bar.component.html',
  styleUrls: ['./search-bar.component.scss']
})
export class SearchBarComponent implements OnInit {

  @Output() searchValue = new EventEmitter<string>()
  searchForm: FormGroup;

  constructor( private fb: FormBuilder, private router: Router ) {}

  ngOnInit(): void {
    this.formInit();
  }

  formInit(){
    this.searchForm = this.fb.group({
      nameItem: '',
    })
  }

  navigateHome(){
    this.router.navigate([`/`])
  }

  emitValue(value){
    this.searchValue.emit(value);
  }
}

<nav class="navBar">

    <a (click)="navigateHome()" class="navBar--logo">
        <img src="../../../assets/Logo_ML.png" alt="ML logo" class="navBar--logo--img">
    </a>

    <input-search class="navBar--input" (searchValue)="emitValue($event)"></input-search>
</nav>

// front-end-react/src/components/SearchBar/index.js
import { Input } from 'antd';
import 'antd/dist/antd.css';
import { useNavigate } from 'react-router-dom';

import { setValue } from 'services/localStorageServices';
import logo from '../../Assets/Logo_ML.png';
import styles from './styles.module.scss'; 

export const SearchBar = ({placeholder}) => {
    const navigate = useNavigate()
    const { Search } = Input

    const onSearch = (value)=>{
        setValue('searchParam', value)
        navigate(`/items?search=${value}`)
    }

    return ( 
        <nav className={styles.navBar}>
            <img src={logo} alt="meliLatam" className={styles.logo}/>   
            <Search placeholder={placeholder} onSearch={onSearch} className={styles.search} />
        </nav>
    )
}
