// front-end-react/src/Screens/Home/index.js
import logo from 'Assets/Logo_ML@2x.png.png'
import styles from './styles.module.scss'; 


export const Home = () => {
    return (
        <div className={styles.home}>
            <div className={styles.message}>
                <img src={logo} alt="a" />
                <h1>Encontrá eso que estás buscando</h1>
            </div>
        </div>
    )
}

// front-end-angular/src/app/components/home-component/page/home.component.ts
import { Component, OnInit } from '@angular/core';
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit{ //OnDestroy {

  constructor(){}

  ngOnInit(): void {
  }
}

<search-bar></search-bar>

<div class="homeContainer">
    <div class="homeContainer__contenedor">
        <img src='../../../../assets/Logo_ML@2x.png.png' alt="Logo" class="homeContainer__contenedor--img"/>
        <h1 class="homeContainer__contenedor--h1">Encontrá eso que estás buscando</h1>
    </div>
</div>
